### DISCUSSION TITLE
Stop displaying song cover?

### DISCUSSION THREAD

**Discussion by harmsthilo** [Fabrizz/MMM-OnSpotify#49] [Q&A] [answered]
Hi,
really appreciating the module. just wondering if it would be possible to not display the song cover, just the song info and the timeline underneath?
thanks in advance!

**Comment by Fabrizz** [comment, marked as answer]
Hi, I had the code, but it would break the CSS calcs for the color blobs, etc. I think that the best idea would be to add:
```css
/* Hides the song/podcast cover, you should set spotifyCodeExperimentalShow to false */
/* This also moves the background color blobs */
.ONSP-Custom .player .swappable {
    display: none !important;
}
```
To your `css/custom.css` file in MM2. (If you add it to the modules custom.css, it get overwritten if you update it)
