### ISSUE TITLE
Hey! Any chance of adjusting the size of the cover art?

### ISSUE THREAD

**Issue by TheEpicTen** [Fabrizz/MMM-OnSpotify#5]
I'm trying to use this module in position: "top_right", under 3 other modules, and the cover art is far too big, I can't see the other info. Can you make this an option?
Thanks!

**Comment by Fabrizz** [comment]
You can use css to change anything that is related to sizing/style.
You can use MM2 custom css or the module custom css:

#### Inside `modules/MMM-OnSpotify/css/custom.css` add:
```css
.ONSP-Custom {
  /* Font size controls all the relative sizings */
  font-size: 16px;
}
```

#### You can also adjust just the media relative size: (not recommended)
```css
.ONSP-Custom {
  --ONSP-INTERNAL-PLAYER-SIZE-WIDTH: 13em
}
```
