### ISSUE TITLE
Always appears left aligned and to small

### ISSUE THREAD

**Issue by enricocirne** [Fabrizz/MMM-OnSpotify#51]
I am just trying to place this module in the middle_center, but it always appears to the left side of the middle. 

Is there a way to get it in the very center? And is there an option to make it appear bigger? width: xx and height: xx are not working

**Comment by Fabrizz** [comment]
Styling should be done using your MM2 `css/custom.css`.
What do you want to achieve? In the middle + bigger or a full screen module?

**Comment by Fabrizz** [comment]
You can add this to your custom.css file to male it appear in the center (thanks for pointing this out, will be a fix in the next update) and to make it bigger:
```css
/* MMM-OnSpotify | Center module, make it bigger */
.MMM-OnSpotify.module {
    display: flex !important;
    justify-content: center !important;

    /* Size iscalculated based on font-size */
    font-size: 24px !important; /* or 30px, 40px, etc*/
}
```

**Comment by Colinwehrhan** [comment]
Hey I ran into this as well. I think a lot of ppl are using this module as a standalone monitor for their living room. Maybe also look into making "fullscreen_above" or "fullscreen_below".

I did a little bit of a hacky way to get around this. In my /home/colinwehrhan/MagicMirror/css/custom.css:
```css
body  {
transform:scale(2.0);
}

.region.bottom.center {
  transform:translateY(-70%);
  }
```

**Comment by Colinwehrhan** [comment]
Never mind, my hacky way the ablum art and the now playing would move around. I ended up doing this to my custom.css:

```css
body  {
transform:scale(2.0);
}

/*
.region.bottom.center {
  transform: translateX(-50%) translateY(-90%);
  }
*/

/* MMM-OnSpotify | Center module, make it bigger */
.MMM-OnSpotify.module {
    display: flex !important;
    justify-content: center !important;

    /* Size is calculated based on font-size */
    font-size: 24px !important; /* or 30px, 40px, etc*/
}
```

**Comment by Fabrizz** [comment]
You should be able to remove the `transform: scale(2.0);` and just change the `font-size`, but the background needs to be manually scaled

**Comment by Colinwehrhan** [comment]
Sounds good, I'll try that out. Any way to make the play bar bigger? 
![IMG_0464](https://github.com/Fabrizz/MMM-OnSpotify/assets/25464209/228de8bb-e449-480f-a4a6-2a55e1c4f8dd)
Looks pretty sick already on the retro setup!

**Comment by Fabrizz** [comment]
```css
.ONSP-Base .player .footer {
    --CUSTOM-FOOTER-WIDTH: 500px
    width: var(--CUSTOM-FOOTER-WIDTH);
    translate: calc((var(--ONSP-INTERNAL-PLAYER-SIZE-WIDTH) - var(--CUSTOM-FOOTER-WIDTH)) /2) 0px;
}
```
