### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by greedyvegan** [Fabrizz/MMM-OnSpotify#57]
1 - is it possible to use the current song's album colors as the theme?
2 - how can I apply other items (background colors) to change with the current song?

**Comment by Fabrizz** [comment]
### 1
Currently no, as it would mean downloading 2 images per song, and that data is not passed from the node_helper (And I don't know if its exposed directly by the current player or I need to send anotherAPI call to get the album data)

### 2
You can use `experimentalCSSOverridesForMM2` [link](https://github.com/Fabrizz/MMM-OnSpotify#theming-3rd-party-modules)

Here you would use the option with CSS variables to change other styles, example to set the background:

```js
experimentalCSSOverridesForMM2: [
    ["--color-background", "background"] // Background is the module reference to a muted background color from the palette, you could use ex.: "palette_muteddark"
]
```

**Comment by greedyvegan** [comment]
forgive me for being slow, can I target specific modules and or their backgrounds or specific text to adhere to the theme?

**Comment by Fabrizz** [comment]
You need to add CSS variables to your `css/custom.css` in your magic mirror file: ([More info on CSS vars](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties))


```css
/* css/custom.css */
:root {
  --my-new-color-variable: #fff; /* A new css variable, with white as default */
}

.module-name { /* Check using the devtools the module name */
   background-color: var(--my-new-color-variable) !important;
}
```

```js
/* In module config */
experimentalCSSOverridesForMM2: [
    ["--color-background", "background", "#fff"]
]
```
