### ISSUE TITLE
Highly Configurable/Customizable

### ISSUE THREAD

**Issue by greedyvegan** [Fabrizz/MMM-OnSpotify#65]
can I change the height & width of the album art/cover?
(or the module overall?)
I have a module I want to hide while spotify is playing so when its not playing the other module is visible.

<img width="237" alt="Screenshot 2024-04-16 at 8 11 39 PM" src="https://github.com/Fabrizz/MMM-OnSpotify/assets/128918275/cee1877d-e8ba-466d-8892-c2725f57b8ab">

I want to cover the entire module with the spotify module.
Do I make changes in the magicmirror/modules/MMM-OnSpotify/css/custom.css or magicmirror/css/custom.css?

**Comment by Fabrizz** [comment]
You should make changes to `magicmirror/css/custom.css` as they don't get overwritten. You can change the module size using
### `magicmirror/css/custom.css`
```css
/* MMM-OnSpotify | Change sizes */
.MMM-OnSpotify.module {
    /* Size is calculated based on font-size */
    font-size: 24px !important; /* or 20px, 18px, etc*/
}
```
You can use CSS :has :is to select stuff from other sibllings
(change **newsfeed** to your module name or how its namedin the css)
(If the chromium browser version older than 2022, it maybe does not have :has:is support)
### `magicmirror/css/custom.css`
```css 
/* MMM-OnSpotify | Opacity of third party based on state */
.region:has(.ONSP-Custom .playing) :is(.module.newsfeed) {
  opacity: 0 !important;
}
.module.newsfeed {
  transition: opacity 500s;
  opacity: 1 !important;
}
```

https://github.com/Fabrizz/MMM-OnSpotify/assets/65259076/9cccf071-1603-43b1-83f7-e471f0db6b6d
