### ISSUE TITLE
Is it possible to remove the album cover?

### ISSUE THREAD

**Issue by thudrox** [Fabrizz/MMM-OnSpotify#95]
Is it possible to remove the album cover and only have track/album/artist, code etc? Think its demanding too much from my RP.

**Comment by Fabrizz** [comment]
You can try disabling all the animations: (or even disabling the [color processing](https://github.com/Fabrizz/MMM-OnSpotify?tab=readme-ov-file#other)!)
```js
{
    module: "MMM-OnSpotify",
    position: "bottom_right",
    config: {

        /* [...] */

        mediaAnimations: false,
        fadeAnimations: false,
        scrollAnimations: false,
        textAnimations: false,
        transitionAnimations: false,
        spotifyVectorAnimations: false,
    },
},
```

If its still too much or you dont want the album art you can add the following to your `<MagicMirror>/css/custom.css`
```css
  .MMM-OnSpotify .ONSP-Custom .swappable {
    display: none !important; /* Hides the album/canvas */
  }
```
